(function(){
  'use strict';
  const cfg=window.CONTENT_CMS_SUPABASE||{};
  const configured=/^https:\/\/[a-z0-9-]+\.supabase\.co$/i.test(cfg.url||'')&&!String(cfg.publishableKey||'').startsWith('YOUR_');
  const client=configured&&window.supabase?.createClient?window.supabase.createClient(cfg.url,cfg.publishableKey):null;
  const $=(selector)=>document.querySelector(selector); const $$=(selector)=>[...document.querySelectorAll(selector)];
  const form=$('#contentForm'); let items=[];let filter='all';let search='';let session=null;let activeId='';let dirty=false;let saveTimer=null;
  const status=(element,message,error=false)=>{element.textContent=message;element.classList.toggle('is-error',error)};
  const escapeText=(value)=>String(value??'').replace(/[&<>"']/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const slugify=(value)=>String(value||'').toLowerCase().trim().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
  const isAdmin=(user)=>user?.app_metadata?.role==='admin';
  const relativeTime=(date)=>{const delta=Date.now()-new Date(date).getTime();const mins=Math.max(1,Math.round(delta/60000));if(mins<60)return `${mins}m ago`;const hours=Math.round(mins/60);if(hours<24)return `${hours}h ago`;const days=Math.round(hours/24);return `${days}d ago`};
  const blockEditor=$('#blockEditor');
  const blockPlaceholder={paragraph:'Write a paragraph…',heading:'Add a section heading…',quote:'Add a quotation…'};
  let savedTextRange=null;
  function rememberTextSelection(){const selection=window.getSelection();if(!selection?.rangeCount)return;const range=selection.getRangeAt(0);const container=range.commonAncestorContainer.nodeType===Node.TEXT_NODE?range.commonAncestorContainer.parentElement:range.commonAncestorContainer;if(container?.closest?.('.block-editable'))savedTextRange=range.cloneRange()}
  function selectionElement(node){return node?.nodeType===Node.TEXT_NODE?node.parentElement:node}
  function applyTextCommand(command){if(!savedTextRange||savedTextRange.collapsed)return status($('#editorStatus'),'Select some text inside a text block first.',true);const selection=window.getSelection();selection.removeAllRanges();selection.addRange(savedTextRange);if(command==='italic'){const startEm=selectionElement(savedTextRange.startContainer)?.closest('em,i');const endEm=selectionElement(savedTextRange.endContainer)?.closest('em,i');if(startEm&&startEm===endEm){const parent=startEm.parentNode;while(startEm.firstChild)parent.insertBefore(startEm.firstChild,startEm);startEm.remove();savedTextRange=null}else{const wrapper=document.createElement('em');wrapper.append(savedTextRange.extractContents());savedTextRange.insertNode(wrapper);savedTextRange.selectNodeContents(wrapper);selection.removeAllRanges();selection.addRange(savedTextRange)}}else if(command==='createLink'){const url=prompt('Paste the link URL');if(!url)return;selection.removeAllRanges();selection.addRange(savedTextRange);document.execCommand(command,false,url)}else document.execCommand(command,false,null);rememberTextSelection();serializeBlocks();markDirty()}
  function applyTextColour(colour){if(!savedTextRange||savedTextRange.collapsed)return status($('#editorStatus'),'Select some text inside a text block first.',true);const selection=window.getSelection();selection.removeAllRanges();selection.addRange(savedTextRange);const wrapper=document.createElement('span');wrapper.style.color=colour;wrapper.append(savedTextRange.extractContents());savedTextRange.insertNode(wrapper);savedTextRange.selectNodeContents(wrapper);selection.removeAllRanges();selection.addRange(savedTextRange);rememberTextSelection();serializeBlocks();markDirty()}
  function blockType(node){const tag=node.tagName?.toLowerCase();if(tag==='h2'||tag==='h3')return 'heading';if(tag==='blockquote')return 'quote';if(tag==='img'||node.querySelector?.('img'))return 'image';if(tag==='video'||node.querySelector?.('video'))return 'video';if(tag==='p')return 'paragraph';return 'html'}
  function mediaBlockMarkup(type,url='',caption=''){const isVideo=type==='video';const accept=isVideo?'video/mp4,video/webm':'image/jpeg,image/png,image/webp,image/gif';const label=isVideo?'video':'image';return `<div class="media-block"><label class="media-drop"><input class="block-file" type="file" accept="${accept}"><span class="media-empty"><i class="${isVideo?'ri-video-add-line':'ri-image-add-line'}"></i><strong>Drop or choose ${label}</strong><span>${isVideo?'MP4 or WebM · max 100 MB':'JPG, PNG, WebP or GIF · max 2 MB'}</span></span></label><div class="media-url-row"><input class="block-media-url" type="text" value="${escapeText(url)}" placeholder="Paste an image or video URL"><button class="button button-secondary apply-media-url" type="button">Use URL</button>${!isVideo?'<button class="button button-secondary set-block-cover" type="button"><i class="ri-image-check-line"></i> Set as cover</button>':''}</div><input class="media-caption" type="text" value="${escapeText(caption)}" placeholder="Caption (optional)"><span class="block-upload-status"></span></div>`}
  function blockInserter(){return `<div class="block-inserter" aria-label="Insert a block here"><span></span><div><button type="button" data-insert-after="paragraph" title="Insert text"><i class="ri-text"></i></button><button type="button" data-insert-after="heading" title="Insert heading"><i class="ri-h-2"></i></button><button type="button" data-insert-after="image" title="Insert image"><i class="ri-image-line"></i></button><button type="button" data-insert-after="video" title="Insert video"><i class="ri-video-line"></i></button><button type="button" data-insert-after="quote" title="Insert quote"><i class="ri-double-quotes-l"></i></button></div><span></span></div>`}
  function createBlock(type='paragraph',data={}){const block=document.createElement('article');block.className='content-block';block.dataset.type=type;if(data.tag)block.dataset.tag=data.tag;block.innerHTML=`<div class="block-rail"><button class="drag-handle" draggable="true" type="button" aria-label="Drag to reorder" title="Drag to reorder"><i class="ri-draggable"></i></button><button class="block-action move-up" type="button" aria-label="Move block up" title="Move up"><i class="ri-arrow-up-s-line"></i></button><button class="block-action move-down" type="button" aria-label="Move block down" title="Move down"><i class="ri-arrow-down-s-line"></i></button><button class="block-action delete" type="button" aria-label="Delete block" title="Delete block"><i class="ri-delete-bin-6-line"></i></button></div><div class="block-surface">${type==='image'||type==='video'?mediaBlockMarkup(type,data.url||'',data.caption||''):`<div class="block-editable" contenteditable="true" role="textbox" data-placeholder="${blockPlaceholder[type]||'Edit content…'}">${data.html||''}</div>`}${blockInserter()}</div>`;if(type==='image'||type==='video')refreshMediaBlock(block);return block}
  function refreshMediaBlock(block){const type=block.dataset.type;const url=block.querySelector('.block-media-url').value.trim();const drop=block.querySelector('.media-drop');const input=drop.querySelector('input');const empty=`<span class="media-empty"><i class="${type==='video'?'ri-video-add-line':'ri-image-add-line'}"></i><strong>Drop or choose ${type}</strong><span>${type==='video'?'MP4 or WebM · max 100 MB':'JPG, PNG, WebP or GIF · max 2 MB'}</span></span>`;drop.querySelectorAll('img,video,.media-empty').forEach((node)=>node.remove());if(url){const media=document.createElement(type==='video'?'video':'img');media.src=url;if(type==='video'){media.controls=true;media.preload='metadata';media.playsInline=true}else media.alt=block.querySelector('.media-caption').value.trim();media.addEventListener('error',()=>{if(!drop.querySelector('.media-empty'))drop.insertAdjacentHTML('beforeend',empty)},{once:true});drop.append(media)}else drop.insertAdjacentHTML('beforeend',empty);drop.append(input)}
  function renderBlocks(html=''){blockEditor.innerHTML='';const template=document.createElement('template');template.innerHTML=String(html||'').trim();const nodes=[...template.content.children];if(!nodes.length){blockEditor.append(createBlock());return}nodes.forEach((node)=>{const type=blockType(node);if(type==='image'||type==='video'){const media=type==='image'?(node.matches('img')?node:node.querySelector('img')):(node.matches('video')?node:node.querySelector('video'));const source=type==='video'?(media?.getAttribute('src')||media?.querySelector('source')?.getAttribute('src')):media?.getAttribute('src');blockEditor.append(createBlock(type,{url:source||'',caption:node.querySelector?.('figcaption')?.textContent||media?.getAttribute('alt')||''}))}else if(type==='html')blockEditor.append(createBlock(type,{html:node.outerHTML}));else blockEditor.append(createBlock(type,{html:node.innerHTML,tag:node.tagName.toLowerCase()}))});}
  function serializeBlocks(){const cover=form.elements.cover_url.value.trim();const html=[...blockEditor.children].map((block)=>{const type=block.dataset.type;if(type==='image'||type==='video'){const url=block.querySelector('.block-media-url').value.trim();if(!url||(type==='image'&&url===cover))return '';const caption=block.querySelector('.media-caption').value.trim();const media=type==='image'?`<img src="${escapeText(url)}" alt="${escapeText(caption)}" loading="lazy">`:`<video controls preload="metadata" playsinline><source src="${escapeText(url)}"></video>`;return `<figure class="article-${type}">${media}${caption?`<figcaption>${escapeText(caption)}</figcaption>`:''}</figure>`}const editable=block.querySelector('.block-editable');const content=editable.innerHTML.trim();if(!content)return '';if(type==='html')return content;const tag=type==='heading'?(block.dataset.tag||'h2'):type==='quote'?'blockquote':'p';return `<${tag}>${content}</${tag}>`}).filter(Boolean).join('\n');form.elements.body_html.value=html;return html}
  function addBlock(type,referenceBlock=null,position='after'){const block=createBlock(type);const anchor=referenceBlock||blockEditor.querySelector('.is-selected');if(anchor?.parentElement===blockEditor){if(position==='before')anchor.before(block);else anchor.after(block)}else blockEditor.append(block);$$('.content-block').forEach((item)=>item.classList.toggle('is-selected',item===block));block.scrollIntoView({behavior:'smooth',block:'center'});block.querySelector('.block-editable')?.focus();markDirty()}
  async function uploadBlockFile(block,file){const type=block.dataset.type;const message=block.querySelector('.block-upload-status');if(!file)return;if(type==='image'&&!file.type.startsWith('image/'))return status(message,'Choose an image file.',true);if(type==='video'&&!file.type.startsWith('video/'))return status(message,'Choose an MP4 or WebM video.',true);if(type==='image'&&file.size>2*1024*1024)return status(message,'Images must be 2 MB or smaller.',true);if(type==='video'&&file.size>100*1024*1024)return status(message,'Videos must be 100 MB or smaller.',true);const extension=(file.name.split('.').pop()||'file').toLowerCase();const path=`${type}/${new Date().toISOString().slice(0,10)}/${crypto.randomUUID()}-${slugify(file.name.replace(/\.[^.]+$/,''))}.${extension}`;status(message,'Uploading 0%…');try{if(file.size>6*1024*1024)await resumableUpload(file,path,(percent)=>status(message,`Uploading ${percent}%…`));else await uploadSmallFile(file,path,(percent)=>status(message,`Uploading ${percent}%…`));const {data}=client.storage.from(cfg.mediaBucket).getPublicUrl(path);block.querySelector('.block-media-url').value=data.publicUrl;refreshMediaBlock(block);serializeBlocks();markDirty();status(message,'Uploaded. Save or publish to keep it.')}catch(error){status(message,error.message||'Upload failed.',true)}}
  function moveBlock(block,direction){const sibling=direction<0?block.previousElementSibling:block.nextElementSibling;if(!sibling)return;if(direction<0)blockEditor.insertBefore(block,sibling);else blockEditor.insertBefore(sibling,block);serializeBlocks();markDirty();block.scrollIntoView({block:'nearest'})}
  async function sendRecoveryEmail(email,redirectTo){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),12000);try{const response=await fetch(`${cfg.url}/auth/v1/recover?redirect_to=${encodeURIComponent(redirectTo)}`,{method:'POST',headers:{apikey:cfg.publishableKey,Authorization:`Bearer ${cfg.publishableKey}`,'Content-Type':'application/json'},body:JSON.stringify({email}),signal:controller.signal});let payload={};try{payload=await response.json()}catch(_error){}if(!response.ok)throw new Error(payload.msg||payload.message||payload.error_description||`Supabase returned ${response.status}.`)}catch(error){if(error.name==='AbortError')throw new Error('Supabase did not respond within 12 seconds. Check your internet connection and try again.');throw error}finally{clearTimeout(timer)}}

  function setSaveState(message,tone='ready'){$('#saveState span').textContent=message;$('#saveState i').className=tone==='saving'?'ri-loader-4-line':tone==='dirty'?'ri-edit-circle-line':'ri-checkbox-circle-line';}
  function updateCounts(){const template=document.createElement('template');template.innerHTML=form.elements.body_html.value;const text=[form.elements.title.value,form.elements.excerpt.value,template.content.textContent].join(' ').trim();const words=text?text.split(/\s+/).length:0;$('#wordCount').textContent=`${words} ${words===1?'word':'words'}`;$('#characterCount').textContent=`${text.length.toLocaleString()} characters`;$('#readingTime').textContent=`${Math.max(1,Math.ceil(words/220))} min read`;}
  function autoGrow(element){element.style.height='auto';element.style.height=`${Math.max(element.scrollHeight,element===form.elements.title?58:70)}px`;}
  function updateChrome(){const type=form.elements.type.value;const title=form.elements.title.value.trim()||`New ${type==='blog'?'post':'project'}`;$('#breadcrumbType').textContent=type==='blog'?'Blog posts':'Projects';$('#breadcrumbTitle').textContent=title;$('#publishButton').textContent=form.elements.status.value==='published'?'Update':'Publish';$('#statusHelp').textContent=form.elements.status.value==='published'?'This content is visible to the public.':'Drafts are not visible to the public.';}
  function installEditorImageUploads(){const composer=$('.block-composer');if(!composer||$('#editorImageUploads'))return;const panel=document.createElement('section');panel.id='editorImageUploads';panel.className='editor-image-uploads';panel.setAttribute('aria-label','Blog cover image');panel.innerHTML=`<div class="editor-image-card"><div class="editor-cover-heading"><div><strong>Blog cover image</strong><p>Always shown at the top and on homepage cards in a 1920 × 1080 frame.</p></div><label class="button button-secondary image-upload-button">Replace cover<input id="coverImageFile" type="file" accept="image/jpeg,image/png,image/webp,image/gif"></label></div><div class="editor-image-preview" id="coverImagePreview"><span class="cover-empty"><i class="ri-image-add-line"></i><strong>Upload a 16:9 cover image</strong><small>Recommended size: 1920 × 1080</small></span></div><span class="image-upload-status" id="coverImageStatus">JPG, PNG, WebP or GIF · max 2 MB</span></div>`;composer.before(panel);$('#coverImageFile').addEventListener('change',(event)=>uploadEditorImage(event.target.files[0]));refreshCoverPreview()}
  function refreshCoverPreview(){const preview=$('#coverImagePreview');if(!preview)return;const url=form.elements.cover_url.value.trim();const empty='<span class="cover-empty"><i class="ri-image-add-line"></i><strong>Upload a 16:9 cover image</strong><small>Recommended size: 1920 × 1080</small></span>';preview.innerHTML=url?`<img src="${escapeText(url)}" alt="Cover image preview">`:empty;const image=preview.querySelector('img');if(image)image.addEventListener('error',()=>{preview.innerHTML=empty},{once:true})}
  async function uploadSmallFile(file,path,onProgress){const {data:{session:active}}=await client.auth.getSession();if(!active)throw new Error('Your session expired. Sign in again.');const objectPath=path.split('/').map(encodeURIComponent).join('/');await new Promise((resolve,reject)=>{const request=new XMLHttpRequest();request.open('POST',`${cfg.url}/storage/v1/object/${encodeURIComponent(cfg.mediaBucket)}/${objectPath}`);request.timeout=25000;request.setRequestHeader('Authorization',`Bearer ${active.access_token}`);request.setRequestHeader('apikey',cfg.publishableKey);request.setRequestHeader('Content-Type',file.type||'application/octet-stream');request.setRequestHeader('x-upsert','false');request.setRequestHeader('cache-control','3600');request.upload.onprogress=(event)=>{if(event.lengthComputable)onProgress(Math.round(event.loaded/event.total*100))};request.onerror=()=>reject(new Error('The browser could not connect to Supabase Storage. Disable strict tracking protection for this local page and try again.'));request.ontimeout=()=>reject(new Error('The image upload timed out. Check your connection and try again.'));request.onload=()=>{let payload={};try{payload=JSON.parse(request.responseText||'{}')}catch(_error){}if(request.status>=200&&request.status<300)resolve(payload);else reject(new Error(payload.message||payload.error||`Upload failed with status ${request.status}.`))};request.send(file)})}
  async function uploadEditorImage(file){const input=$('#coverImageFile');const message=$('#coverImageStatus');if(!file)return;if(!file.type.startsWith('image/')){status(message,'Choose an image file.',true);input.value='';return}if(file.size>2*1024*1024){status(message,'This image is larger than 2 MB. Compress it and try again.',true);input.value='';return}status(message,'Uploading 0%…');input.disabled=true;const extension=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`images/${new Date().toISOString().slice(0,10)}/${crypto.randomUUID()}-${slugify(file.name.replace(/\.[^.]+$/,''))}.${extension}`;try{await uploadSmallFile(file,path,(percent)=>status(message,`Uploading ${percent}%…`));const {data}=client.storage.from(cfg.mediaBucket).getPublicUrl(path);form.elements.cover_url.value=data.publicUrl;refreshCoverPreview();markDirty();status(message,'Cover uploaded. Save or publish to keep it.')}catch(error){console.error('Cover upload failed.',error);status(message,error.message||'Image upload failed.',true)}finally{input.disabled=false;input.value=''}}

  async function boot(){
    if(!client){const msg='Database not configured. Check assets/js/supabase-config.js: URL='+(cfg.url||'missing')+', Key='+(cfg.publishableKey?.substring(0,20)||'missing')+'...';status($('#loginStatus'),msg,true);return}
    const authError=new URLSearchParams(location.hash.slice(1)).get('error_description');
    if(authError)status($('#loginStatus'),decodeURIComponent(authError.replace(/\+/g,' ')),true);
    client.auth.onAuthStateChange((event,next)=>{session=next;if(event==='PASSWORD_RECOVERY')openNewPasswordDialog();renderSession()});
    try{const {data}=await client.auth.getSession();session=data.session;renderSession();if(session&&new URLSearchParams(location.search).get('reset')==='1')openNewPasswordDialog()}catch(error){console.error('Auth boot error:',error);status($('#loginStatus'),'Connection failed: '+error.message,true)}
  }
  function openNewPasswordDialog(){const dialog=$('#newPasswordDialog');if(!dialog.open)dialog.showModal();setTimeout(()=>dialog.querySelector('input').focus(),0)}
  function renderSession(){const authed=Boolean(session&&isAdmin(session.user));$('#loginPanel').hidden=authed;$('#studio').hidden=!authed;$('#sessionEmail').textContent=authed?session.user.email:'';if(session&&!authed){status($('#loginStatus'),'This account does not have permission to manage content.',true);client.auth.signOut()}if(authed){loadItems();loadBrandSettings()}}
  async function loadItems(preferredId=activeId){setSaveState('Loading…','saving');const {data,error}=await client.from('content_items').select('*').order('updated_at',{ascending:false});if(error){status($('#editorStatus'),error.message,true);setSaveState('Could not load','dirty');return}items=data||[];renderList();if(preferredId&&items.some((item)=>item.id===preferredId))editItem(preferredId,false);else if(!activeId)newItem(false);setSaveState('All changes saved')}
  function renderList(){const term=search.toLowerCase();const visible=items.filter((item)=>(filter==='all'||item.type===filter)&&(!term||`${item.title} ${item.excerpt} ${(item.tags||[]).join(' ')}`.toLowerCase().includes(term)));$('#contentCount').textContent=`${visible.length} ${visible.length===1?'item':'items'}`;$('#contentList').innerHTML=visible.length?visible.map((item)=>`<button class="content-item ${activeId===item.id?'is-active':''}" data-id="${item.id}"><i class="${item.type==='blog'?'ri-file-text-line':'ri-folder-line'}"></i><span><strong>${escapeText(item.title)}</strong><span class="${item.status}">${item.status==='published'?'Published':'Draft'} · ${relativeTime(item.updated_at)}</span></span></button>`).join(''):'<p class="field-help">No matching content.</p>'}
  function newItem(focus=true){activeId='';form.reset();form.elements.id.value='';form.elements.type.value='blog';form.elements.status.value='draft';form.elements.sort_order.value='100';renderBlocks('');$('#deleteButton').hidden=true;status($('#editorStatus'),'');dirty=false;clearTimeout(saveTimer);localStorage.removeItem('cms-new-draft');serializeBlocks();updateCounts();updateChrome();refreshCoverPreview();renderList();['title','excerpt'].forEach((name)=>autoGrow(form.elements[name]));if(focus)form.elements.title.focus();closeMobilePanels()}
  function editItem(id,scroll=true){const item=items.find((entry)=>entry.id===id);if(!item)return;activeId=id;Object.entries(item).forEach(([key,value])=>{const field=form.elements[key];if(!field)return;if(field.type==='checkbox')field.checked=Boolean(value);else if(key==='tags')field.value=(value||[]).join(', ');else field.value=value??''});renderBlocks(item.body_html||'');$('#deleteButton').hidden=false;dirty=false;updateCounts();updateChrome();refreshCoverPreview();renderList();['title','excerpt'].forEach((name)=>autoGrow(form.elements[name]));if(scroll)document.querySelector('.editor-canvas').scrollTo({top:0,behavior:'smooth'});closeMobilePanels()}
  function markDirty(){serializeBlocks();dirty=true;setSaveState('Unsaved changes','dirty');updateCounts();updateChrome();clearTimeout(saveTimer);saveTimer=setTimeout(()=>{if(!activeId)localStorage.setItem('cms-new-draft',JSON.stringify(Object.fromEntries(new FormData(form))));setSaveState(activeId?'Unsaved changes':'Draft saved locally','dirty')},700)}
  async function save(event){event?.preventDefault();serializeBlocks();if(!form.reportValidity())return;setSaveState('Saving…','saving');const values=Object.fromEntries(new FormData(form));const id=values.id;delete values.id;values.title=values.title.trim();values.slug=slugify(values.slug||values.title);values.tags=String(values.tags||'').split(',').map((tag)=>tag.trim()).filter(Boolean);values.featured=form.elements.featured.checked;values.sort_order=Number(values.sort_order)||100;values.author_id=session.user.id;values.updated_at=new Date().toISOString();values.published_at=values.status==='published'?(items.find((item)=>item.id===id)?.published_at||new Date().toISOString()):null;const query=id?client.from('content_items').update(values).eq('id',id).select('id').single():client.from('content_items').insert(values).select('id').single();const {data,error}=await query;if(error){status($('#editorStatus'),error.message,true);setSaveState('Save failed','dirty');return}activeId=data.id;dirty=false;localStorage.removeItem('cms-new-draft');status($('#editorStatus'),values.status==='published'?'Published successfully.':'Draft saved.');setSaveState('All changes saved');await loadItems(activeId)}
  async function publish(){form.elements.status.value='published';updateChrome();await save()}
  async function remove(){if(!activeId||!confirm('Permanently delete this content item? Uploaded media will remain in the media library.'))return;const button=$('#deleteButton');const id=activeId;button.disabled=true;status($('#editorStatus'),'Deleting…');const {data,error}=await client.from('content_items').delete().eq('id',id).select('id').maybeSingle();button.disabled=false;if(error){status($('#editorStatus'),error.message,true);return}if(!data){status($('#editorStatus'),'Nothing was deleted. Sign out and back in, then try again.',true);return}activeId='';newItem(false);await loadItems();status($('#editorStatus'),'Content deleted.')}
  function preview(){serializeBlocks();const title=escapeText(form.elements.title.value||'Untitled content');const excerpt=escapeText(form.elements.excerpt.value||'');const cover=form.elements.cover_url.value;$('#previewContent').innerHTML=`<h1>${title}</h1>${excerpt?`<p class="preview-deck">${excerpt}</p>`:''}${cover?`<img src="${escapeText(cover)}" alt="">`:''}<div>${form.elements.body_html.value||'<p>No body content yet.</p>'}</div>`;applyPreviewBranding();$('#previewDialog').showModal()}
  async function upload(){const file=$('#mediaFile').files[0];if(!file)return status($('#uploadStatus'),'Choose a file first.',true);if(file.type.startsWith('image/')&&file.size>2*1024*1024)return status($('#uploadStatus'),'Images must be 2 MB or smaller.',true);if(file.size>100*1024*1024)return status($('#uploadStatus'),'Videos and files must be 100 MB or smaller.',true);const target=$('#mediaTarget').value;const button=$('#uploadButton');const progress=$('#uploadProgress');button.disabled=true;progress.hidden=false;progress.value=0;const extension=(file.name.split('.').pop()||'file').toLowerCase();const path=`${form.elements.type.value}/${new Date().toISOString().slice(0,10)}/${crypto.randomUUID()}-${slugify(file.name.replace(/\.[^.]+$/,''))}.${extension}`;try{if(file.size>6*1024*1024)await resumableUpload(file,path,(percent)=>{progress.value=percent;status($('#uploadStatus'),`Uploading ${percent}%…`)});else{const {error}=await client.storage.from(cfg.mediaBucket).upload(path,file,{cacheControl:'3600',upsert:false});if(error)throw error;progress.value=100}const {data}=client.storage.from(cfg.mediaBucket).getPublicUrl(path);form.elements[target].value=data.publicUrl;if(target==='cover_url')refreshCoverPreview();markDirty();status($('#uploadStatus'),'Upload complete. Save or publish to keep this media URL.')}catch(error){status($('#uploadStatus'),error.message||'Upload failed.',true)}finally{button.disabled=false}}
  async function resumableUpload(file,path,onProgress){const {data:{session:active}}=await client.auth.getSession();if(!active)throw new Error('Your session expired. Sign in again.');const projectRef=new URL(cfg.url).hostname.split('.')[0];await new Promise((resolve,reject)=>{new tus.Upload(file,{endpoint:`https://${projectRef}.storage.supabase.co/storage/v1/upload/resumable`,retryDelays:[0,1000,3000,5000],headers:{authorization:`Bearer ${active.access_token}`,apikey:cfg.publishableKey,'x-upsert':'false'},uploadDataDuringCreation:true,removeFingerprintOnSuccess:true,metadata:{bucketName:cfg.mediaBucket,objectName:path,contentType:file.type,cacheControl:'3600'},chunkSize:6*1024*1024,onError:reject,onProgress:(sent,total)=>onProgress(Math.round(sent/total*100)),onSuccess:resolve}).start()})}
  function closeMobilePanels(){$('#contentDrawer').classList.remove('is-open');$('#inspector').classList.remove('is-open')}
  function insertSnippet(snippet){const block=createBlock('html',{html:snippet});blockEditor.append(block);block.scrollIntoView({behavior:'smooth',block:'center'});markDirty()}
  function installEngagementTools(){const bar=$('.format-bar');if(!bar||bar.querySelector('[data-engagement-tool]'))return;const divider=document.createElement('span');divider.className='format-divider';bar.append(divider);[{label:'Key takeaway',icon:'ri-lightbulb-line',snippet:'<aside class="post-callout"><strong>Key takeaway</strong><p>Add the most useful point here.</p></aside>'},{label:'CTA button',icon:'ri-cursor-line',snippet:'<div class="post-cta"><p>Ready to take the next step?</p><a class="cta-button" href="https://">Call to action</a></div>'}].forEach((tool)=>{const button=document.createElement('button');button.type='button';button.title=tool.label;button.setAttribute('aria-label',tool.label);button.dataset.engagementTool='';button.dataset.insert=tool.snippet;button.innerHTML=`<i class="${tool.icon}"></i>`;bar.append(button)})}

  function installTextColourTool(){const bar=$('.format-bar');if(!bar||$('#textColourPicker'))return;const control=document.createElement('label');control.className='text-colour-control';control.title='Text colour';control.setAttribute('aria-label','Choose text colour');control.innerHTML='<i class="ri-font-color"></i><input id="textColourPicker" type="color" value="#e5b91e" aria-label="Text colour">';bar.insertBefore(control,bar.querySelector('[data-engagement-tool]'));$('#textColourPicker').addEventListener('change',(event)=>applyTextColour(event.target.value))}

  const brandDefaults={id:'default',brand_name:'My Site',theme_mode:'dark',light_background:'#f6f4ef',light_text:'#0b0b0b',light_link:'#1710a5',dark_background:'#0c0f12',dark_text:'#f4f5f6',dark_link:'#a894ff'};
  function channel(hex,index){const value=parseInt(hex.slice(1+index*2,3+index*2),16)/255;return value<=.04045?value/12.92:Math.pow((value+.055)/1.055,2.4)}
  function luminance(hex){return .2126*channel(hex,0)+.7152*channel(hex,1)+.0722*channel(hex,2)}
  function contrastRatio(first,second){const values=[luminance(first),luminance(second)].sort((a,b)=>b-a);return (values[0]+.05)/(values[1]+.05)}
  function brandValues(){const panel=$('#brandSettingsForm');return panel?Object.fromEntries(new FormData(panel)):brandDefaults}
  function resolvedBrandTheme(values=brandValues()){return values.theme_mode==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):values.theme_mode}
  function updateBrandPreview(event){const values=brandValues();const editedPalette=event?.target?.name?.match(/^(light|dark)_/)?.[1];const theme=editedPalette||resolvedBrandTheme(values);const background=values[`${theme}_background`];const textColour=values[`${theme}_text`];const link=values[`${theme}_link`];const canvas=$('.editor-canvas');if(canvas){canvas.style.setProperty('--cms-editor-bg',background);canvas.style.setProperty('--cms-editor-text',textColour);canvas.style.setProperty('--cms-editor-link',link)}$$('.branding-palette').forEach((palette)=>{const active=palette.dataset.theme===theme;palette.classList.toggle('is-current',active);palette.querySelector('.palette-state').textContent=active?'Currently shown':'Not currently shown'});const textRatio=contrastRatio(background,textColour);const linkRatio=contrastRatio(background,link);const pass=textRatio>=4.5&&linkRatio>=4.5;const report=$('#brandContrastStatus');report.classList.toggle('is-warning',!pass);report.textContent=`Editor showing ${theme} colours · Text ${textRatio.toFixed(1)}:1 · Links ${linkRatio.toFixed(1)}:1${pass?' · Good contrast':' · Improve contrast'}`}
  function applyPreviewBranding(){const values=brandValues();const theme=resolvedBrandTheme(values);const dialog=$('#previewDialog');dialog.style.setProperty('--cms-preview-bg',values[`${theme}_background`]);dialog.style.setProperty('--cms-preview-text',values[`${theme}_text`]);dialog.style.setProperty('--cms-preview-link',values[`${theme}_link`])}
  function fillBrandSettings(values){const panel=$('#brandSettingsForm');if(!panel)return;Object.entries({...brandDefaults,...values}).forEach(([name,value])=>{if(panel.elements[name])panel.elements[name].value=value});updateBrandPreview()}
  async function loadBrandSettings(){if(!client||!$('#brandSettingsForm'))return;status($('#brandSettingsStatus'),'Loading brand settings…');const {data,error}=await client.from(cfg.brandSettingsTable||'blog_brand_settings').select('*').eq('id','default').maybeSingle();if(error)return status($('#brandSettingsStatus'),error.message,true);fillBrandSettings(data||brandDefaults);status($('#brandSettingsStatus'),'Brand settings are up to date.')}
  async function saveBrandSettings(event){event.preventDefault();const button=$('#saveBrandSettings');button.disabled=true;status($('#brandSettingsStatus'),'Saving…');const values=brandValues();const payload={id:'default',brand_name:String(values.brand_name||'').trim()||'Brand',theme_mode:values.theme_mode,light_background:values.light_background,light_text:values.light_text,light_link:values.light_link,dark_background:values.dark_background,dark_text:values.dark_text,dark_link:values.dark_link,updated_at:new Date().toISOString(),updated_by:session.user.id};const {data,error}=await client.from(cfg.brandSettingsTable||'blog_brand_settings').upsert(payload,{onConflict:'id'}).select().single();button.disabled=false;if(error)return status($('#brandSettingsStatus'),error.message,true);localStorage.removeItem('blog-theme');fillBrandSettings(data);status($('#brandSettingsStatus'),'Saved. Your public blog preview will now use the selected default appearance.')}
  function installBrandingPanel(){const inspector=$('#inspector');if(!inspector||$('#brandSettingsForm'))return;const panel=document.createElement('details');panel.className='inspector-section branding-panel';panel.open=true;panel.innerHTML=`<summary><span><i class="ri-palette-line"></i> Blog branding</span><i class="ri-arrow-down-s-line"></i></summary><form id="brandSettingsForm" class="branding-form"><label><span>Brand name</span><input name="brand_name" type="text" value="${brandDefaults.brand_name}" maxlength="80"></label><label><span>Default appearance</span><select name="theme_mode"><option value="dark">Dark</option><option value="light">Light</option><option value="system">Follow visitor's device</option></select></label>${['light','dark'].map((theme)=>`<fieldset class="branding-palette" data-theme="${theme}"><legend>${theme[0].toUpperCase()+theme.slice(1)} colours <small class="palette-state"></small></legend>${[['background','Body background'],['text','Text'],['link','Links']].map(([role,label])=>`<label class="branding-colour-row"><span>${label}</span><input name="${theme}_${role}" type="color" value="${brandDefaults[`${theme}_${role}`]}"></label>`).join('')}</fieldset>`).join('')}<p id="brandContrastStatus" class="contrast-report"></p><button id="saveBrandSettings" class="button button-primary" type="submit">Save blog branding</button><span id="brandSettingsStatus" class="field-help" aria-live="polite"></span></form>`;inspector.append(panel);const settingsForm=$('#brandSettingsForm');settingsForm.addEventListener('input',updateBrandPreview);settingsForm.addEventListener('submit',saveBrandSettings);fillBrandSettings(brandDefaults)}

  installEngagementTools();installTextColourTool();installBrandingPanel();
  $('#loginForm').addEventListener('submit',async(event)=>{event.preventDefault();const button=event.target.querySelector('button');button.disabled=true;status($('#loginStatus'),'Signing in…');const values=Object.fromEntries(new FormData(event.target));try{const {error}=await client.auth.signInWithPassword(values);button.disabled=false;if(error){let errorMsg=error.message||'Unknown error';if(errorMsg.includes('fetch')||errorMsg.includes('Network'))errorMsg='NetworkError: Cannot reach Supabase. Check your internet connection or try refreshing the page.';else if(errorMsg.includes('Invalid'))errorMsg='Invalid email or password. Check your login credentials.';status($('#loginStatus'),errorMsg,true)}}catch(error){button.disabled=false;console.error('Login error:',error);let msg='Network error. ';if(error.message.includes('fetch'))msg+='Supabase cannot be reached. ';else msg+=error.message;status($('#loginStatus'),msg+'Refresh and try again, or contact support.',true)}});
  $('#forgotPasswordButton').addEventListener('click',()=>$('#recoveryDialog').showModal());
  $('#closeRecovery').addEventListener('click',()=>$('#recoveryDialog').close());
  $('#recoveryForm').addEventListener('submit',async(event)=>{event.preventDefault();const button=event.target.querySelector('button[type="submit"]');const email=String(new FormData(event.target).get('email')||'').trim();button.disabled=true;status($('#recoveryStatus'),'Sending a fresh link…');try{const redirectTo=/^https?:$/.test(location.protocol)?new URL('./?reset=1',location.href).href:'http://127.0.0.1:4182/admin/?reset=1';await sendRecoveryEmail(email,redirectTo);status($('#recoveryStatus'),'Recovery email sent. Use only the newest link; older links will no longer work.')}catch(error){status($('#recoveryStatus'),error.message||'The recovery email could not be sent.',true)}finally{button.disabled=false}});
  $('#newPasswordForm').addEventListener('submit',async(event)=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.target));if(values.password!==values.confirm_password)return status($('#newPasswordStatus'),'The passwords do not match.',true);const button=event.target.querySelector('button[type="submit"]');button.disabled=true;status($('#newPasswordStatus'),'Updating password…');const {error}=await client.auth.updateUser({password:values.password});button.disabled=false;if(error)return status($('#newPasswordStatus'),error.message,true);status($('#newPasswordStatus'),'Password updated. You are signed in.');history.replaceState({},'',location.pathname);setTimeout(()=>{$('#newPasswordDialog').close();renderSession()},700)});
  form.addEventListener('submit',save);form.addEventListener('input',(event)=>{if(event.target.matches('input,textarea,select')){if(event.target===form.elements.title&&!activeId)form.elements.slug.value=slugify(event.target.value);if(event.target===form.elements.cover_url)refreshCoverPreview();if(event.target.matches('.title-input,.deck-input'))autoGrow(event.target);markDirty()}});form.addEventListener('change',(event)=>{if(!event.target.matches('.block-file'))markDirty()});
  $$('[data-add-block]').forEach((button)=>button.addEventListener('click',()=>addBlock(button.dataset.addBlock,null,blockEditor.querySelector('.is-selected')?'before':'after')));
  document.addEventListener('selectionchange',rememberTextSelection);
  $$('[data-command]').forEach((button)=>{button.addEventListener('mousedown',(event)=>event.preventDefault());button.addEventListener('click',()=>applyTextCommand(button.dataset.command))});
  blockEditor.addEventListener('input',(event)=>{if(event.target.matches('.block-editable,.media-caption')){if(event.target.matches('.media-caption'))refreshMediaBlock(event.target.closest('.content-block'));markDirty()}});
  blockEditor.addEventListener('change',(event)=>{if(event.target.matches('.block-file'))uploadBlockFile(event.target.closest('.content-block'),event.target.files[0])});
  blockEditor.addEventListener('click',(event)=>{const block=event.target.closest('.content-block');if(!block)return;$$('.content-block').forEach((item)=>item.classList.toggle('is-selected',item===block));const insertButton=event.target.closest('[data-insert-after]');if(insertButton)addBlock(insertButton.dataset.insertAfter,block);else if(event.target.closest('.delete')){if(blockEditor.children.length===1){block.replaceWith(createBlock());}else block.remove();markDirty()}else if(event.target.closest('.move-up'))moveBlock(block,-1);else if(event.target.closest('.move-down'))moveBlock(block,1);else if(event.target.closest('.apply-media-url')){refreshMediaBlock(block);markDirty()}else if(event.target.closest('.set-block-cover')){const url=block.querySelector('.block-media-url').value.trim();if(!url)return status(block.querySelector('.block-upload-status'),'Add or upload an image first.',true);form.elements.cover_url.value=url;refreshCoverPreview();serializeBlocks();markDirty();status(block.querySelector('.block-upload-status'),'Set as cover. It will not be repeated in the article body.')}});
  blockEditor.addEventListener('dragstart',(event)=>{const block=event.target.closest('.content-block');if(!block)return;block.classList.add('is-dragging');event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/plain','block')});
  blockEditor.addEventListener('dragend',()=>{$$('.content-block').forEach((block)=>block.classList.remove('is-dragging','is-drop-target'))});
  blockEditor.addEventListener('dragover',(event)=>{event.preventDefault();const target=event.target.closest('.content-block');$$('.content-block').forEach((block)=>block.classList.toggle('is-drop-target',block===target&&!block.classList.contains('is-dragging')))});
  blockEditor.addEventListener('drop',(event)=>{event.preventDefault();const dragging=blockEditor.querySelector('.is-dragging');const target=event.target.closest('.content-block');if(!dragging||!target||dragging===target)return;const rect=target.getBoundingClientRect();blockEditor.insertBefore(dragging,event.clientY<rect.top+rect.height/2?target:target.nextSibling);serializeBlocks();markDirty()});
  blockEditor.addEventListener('dragenter',(event)=>{const drop=event.target.closest('.media-drop');if(drop)drop.classList.add('is-over')});blockEditor.addEventListener('dragleave',(event)=>{const drop=event.target.closest('.media-drop');if(drop)drop.classList.remove('is-over')});
  blockEditor.addEventListener('drop',(event)=>{const drop=event.target.closest('.media-drop');if(!drop||!event.dataTransfer.files.length)return;event.preventDefault();event.stopPropagation();drop.classList.remove('is-over');uploadBlockFile(drop.closest('.content-block'),event.dataTransfer.files[0])},true);
  $('#contentSearch').addEventListener('input',(event)=>{search=event.target.value;renderList()});$('#contentList').addEventListener('click',(event)=>{const button=event.target.closest('[data-id]');if(button){if(dirty&&!confirm('Discard unsaved changes and open another item?'))return;editItem(button.dataset.id)}});
  $$('#newItemButton,#newItemFooter').forEach((button)=>button.addEventListener('click',()=>{if(!dirty||confirm('Discard unsaved changes and create new content?'))newItem()}));$$('[data-filter]').forEach((button)=>button.addEventListener('click',()=>{filter=button.dataset.filter;$$('[data-filter]').forEach((item)=>item.classList.toggle('is-active',item===button));renderList()}));$$('[data-insert]').forEach((button)=>button.addEventListener('click',()=>insertSnippet(button.dataset.insert)));
  $('#publishButton').addEventListener('click',publish);$('#previewButton').addEventListener('click',preview);$('#closePreview').addEventListener('click',()=>$('#previewDialog').close());$('#deleteButton').addEventListener('click',remove);$('#uploadButton').addEventListener('click',upload);$('#signOutButton').addEventListener('click',()=>client.auth.signOut());$('#accountButton').addEventListener('click',()=>{const menu=$('#accountMenu');menu.hidden=!menu.hidden;$('#accountButton').setAttribute('aria-expanded',String(!menu.hidden))});$('#allContentButton').addEventListener('click',()=>{$('#contentDrawer').classList.add('is-open')});$('#drawerButton').addEventListener('click',()=>$('#contentDrawer').classList.toggle('is-open'));$('#inspectorButton').addEventListener('click',()=>$('#inspector').classList.add('is-open'));$('#closeInspector').addEventListener('click',()=>$('#inspector').classList.remove('is-open'));
  document.addEventListener('keydown',(event)=>{const key=event.key.toLowerCase();if((event.ctrlKey||event.metaKey)&&key==='s'){event.preventDefault();save()}if((event.ctrlKey||event.metaKey)&&key==='k'){event.preventDefault();$('#contentDrawer').classList.add('is-open');$('#contentSearch').focus()}if((event.ctrlKey||event.metaKey)&&key==='i'&&event.target.closest?.('.block-editable')){event.preventDefault();rememberTextSelection();applyTextCommand('italic')}});window.addEventListener('beforeunload',(event)=>{if(dirty){event.preventDefault();event.returnValue=''}});
  document.addEventListener('input',(event)=>{if(event.target.closest?.('#brandSettingsForm'))status($('#brandSettingsStatus'),'Unsaved colour changes…')});
  document.addEventListener('change',(event)=>{const form=event.target.closest?.('#brandSettingsForm');if(form&&event.target.matches('input[type="color"],select'))form.requestSubmit()});
  installEditorImageUploads();boot();
})();
